apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-mq-native-ha
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/YOUR-USER/rc-mq-helm-argocd.git
    targetRevision: main
    path: .

    helm:
      valueFiles:
        - values/mq-values.yaml
        - values/mqsc-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: mq

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
