replicaCount: 3  # Native HA: 3 replicas (1 active + 2 standby)

resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 2Gi

persistence:
  size: 200Gi

mqsc: |
  DEFINE QLOCAL('QA.QUEUE.1') REPLACE DEFPSIST(YES)
  DEFINE QLOCAL('QA.QUEUE.2') REPLACE DEFPSIST(YES)
  DEFINE QLOCAL('QA.DEAD.LETTER.QUEUE') REPLACE DEFPSIST(YES)
  DEFINE CHANNEL('QA.APP.SVRCONN') CHLTYPE(SVRCONN) REPLACE
  SET CHLAUTH('QA.APP.SVRCONN') TYPE(BLOCKUSER) USERLIST('nobody')
  SET CHLAUTH('*') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS)
  SET CHLAUTH('QA.APP.SVRCONN') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(REQUIRED)
  ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) ADOPTCTX(YES)
  REFRESH SECURITY TYPE(CONNAUTH)
  DEFINE LISTENER('QA.LISTENER.TCP') TRPTYPE(TCP) PORT(1414) REPLACE
  START LISTENER('QA.LISTENER.TCP')
