apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qm1
  namespace: default

spec:
  project: default

  source:
    repoURL: https://github.com/Hoshmohammad/rc-mq-helm-main.git
    targetRevision: HEAD
    path: charts/ibm-mq
    helm:
      releaseName: qm1
      valueFiles:
        - samples/AzureAKS/deploy/secureapp.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true