apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibm-mq.fullname" . }}-config
  labels:
    {{- include "ibm-mq.labels" . | nindent 4 }}
data:
  config.mqsc: |
    {{- .Values.mqsc | nindent 4 }}
  mq.ini: |
    {{- .Values.ini | nindent 4 }}
