apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibm-mq.fullname" . }}-credentials
  labels:
    {{- include "ibm-mq.labels" . | nindent 4 }}
type: Opaque
data:
  adminPassword: {{ .Values.mq.adminPassword | b64enc | quote }}
  appPassword: {{ .Values.mq.appPassword | b64enc | quote }}
