apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibm-mq.fullname" . }}
  labels:
    {{- include "ibm-mq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.mqListener }}
      targetPort: mq-listener
      protocol: TCP
      name: mq-listener
    - port: {{ .Values.service.ports.webConsole }}
      targetPort: web-console
      protocol: TCP
      name: web-console
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ibm-mq.selectorLabels" . | nindent 4 }}
